#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# Определение переменной среды
ENV ConnectionStrings__MyDatabase "Server=sql_server2022;Database=Khotos_Identity;User Id=SA;Password=A&VeryComplex123Password;MultipleActiveResultSets=true;Trust Server Certificate=True;Encrypt=False"


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Clients/WebUI_Wasm/WebUI_Wasm.csproj", "Clients/WebUI_Wasm/"]
COPY ["Shared/SharedModels/SharedModels.csproj", "Shared/SharedModels/"]
RUN dotnet restore "./Clients/WebUI_Wasm/./WebUI_Wasm.csproj"
COPY . .
WORKDIR "/src/Clients/WebUI_Wasm"
RUN dotnet dev-certs https
RUN dotnet build "./WebUI_Wasm.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./WebUI_Wasm.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebUI_Wasm.dll"]