name: CI
on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose
      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
      - name: Run tests
        run: |
          docker exec -it my_web_service_1 bash -c "pytest"
